if (document.images) { 
	var vfold = '../'; 
	if (document.getElementById('is_seo') != null) 
	{ vfold='../'; } 
	if (document.getElementById('is_seo_cat') != null) 
	{ vfold=''; } 
	if (document.getElementById('is_seo_serv') != null) 
	{ vfold=''; } 
	if (document.getElementById('is_seo_faq') != null) 
	{ vfold=''; } 
	if (document.getElementById('is_seo_forum') != null) 
	{ vfold=''; } 
	if (document.getElementById('is_seo_content') != null) 
	{ vfold=''; }


	imageOver[1].src = "../../images/buttons/go_left_f2.gif";
	imageOver[2].src = "../../images/buttons/login_f2.gif";
	imageOver[3].src = "../../images/buttons/logout_f2.gif";
	imageOver[4].src = "../../images/buttons/disclaimer_f2.gif";
	imageOver[5].src = "../../images/buttons/click_to_join_f2.gif";
	imageOver[6].src = "../../images/buttons/edit_user_details_f2.gif";
	imageOver[8].src = "../images/htext_c2_f2.gif";
	imageOver[9].src = "../../images/buttons/view_printable_f2.gif";
	imageOver[10].src = "../../images/buttons/previous_f2.gif";
	imageOver[11].src = "../../images/buttons/next_f2.gif";
	imageOver[12].src = "../../images/buttons/go_f2.gif";
	imageOver[13].src = "../../images/buttons/recent10_f2.gif";
	imageOver[14].src = "../../images/buttons/top10_f2.gif";
	imageOver[15].src = "../../images/buttons/search_f2.gif";
	imageOver[16].src = "../../images/buttons/submit_question_f2.gif";
	imageOver[17].src = "../../images/buttons/cancel_f2.gif";
	imageOver[18].src = "../../images/buttons/submit_f2.gif";
	imageOver[19].src = "../../images/buttons/view_archived_f2.gif";
	imageOver[20].src = "../../images/buttons/back_f2.gif";
	imageOver[21].src = "../../images/buttons/email_a_friend_f2.gif";
	imageOver[22].src = "../../images/buttons/add_update_f2.gif";
	imageOver[23].src = "../../images/buttons/reset_f2.gif";
	imageOver[24].src = "../../images/buttons/unsubscribe_f2.gif";
	imageOver[25].src = "../../images/buttons/view_cart_f2.gif";
	imageOver[26].src = "../../images/buttons/shopping_cart_f2.gif";
	imageOver[27].src = "../../images/buttons/check_out_f2.gif";
	imageOver[28].src = "../../images/buttons/bookmark_page_f2.gif";
	imageOut[1].src = "../../images/buttons/go_left.gif";
	imageOut[2].src = "../../images/buttons/login.gif";
	imageOut[3].src = "../../images/buttons/logout.gif";
	imageOut[4].src = "../../images/buttons/disclaimer.gif";
	imageOut[5].src = "../../images/buttons/click_to_join.gif";
	imageOut[6].src = "../../images/buttons/edit_user_details.gif";
	imageOut[8].src = "../images/htext_c2.gif";
	imageOut[9].src = "../../images/buttons/view_printable.gif";
	imageOut[10].src = "../../images/buttons/previous.gif";
	imageOut[11].src = "../../images/buttons/next.gif";
	imageOut[12].src = "../../images/buttons/go.gif";
	imageOut[13].src = "../../images/buttons/recent10.gif";
	imageOut[14].src = "../../images/buttons/top10.gif";
	imageOut[15].src = "../../images/buttons/search.gif";
	imageOut[16].src = "../../images/buttons/submit_question.gif";
	imageOut[17].src = "../../images/buttons/cancel.gif";
	imageOut[18].src = "../../images/buttons/submit.gif";
	imageOut[19].src = "../../images/buttons/view_archived.gif";
	imageOut[20].src = "../../images/buttons/back.gif";
	imageOut[21].src = "../../images/buttons/email_a_friend.gif";
	imageOut[22].src = "../../images/buttons/add_update.gif";
	imageOut[23].src = "../../images/buttons/reset.gif";
	imageOut[24].src = "../../images/buttons/unsubscribe.gif";
	imageOut[25].src = "../../images/buttons/view_cart.gif";
	imageOut[26].src = "../../images/buttons/shopping_cart.gif";
	imageOut[27].src = "../../images/buttons/check_out.gif";
	imageOut[28].src = "../../images/buttons/bookmark_page.gif";
}//if

